## 8.2.3

In [1]:
import pandas as pd

In [2]:
# Read an excel file 
crowdfunding_data = pd.ExcelFile("../crowdfunding.xlsx")
# Get sheet names
crowdfunding_data.sheet_names

['crowdfunding_info', 'contact_info']

In [3]:
# Transform sheets into dataframes
crowdfunding_info_df = pd.read_excel(crowdfunding_data, sheet_name="crowdfunding_info")
crowdfunding_info_df.head(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays
5,2057,Harris Group,Open-source optimizing database,7600,13195,successful,174,DK,DKK,1607666400,1630213200,False,False,theater/plays
6,1894,"Ortiz, Coleman and Mitchell",Operative upward-trending algorithm,5200,1090,failed,18,GB,GBP,1596171600,1620709200,False,False,film & video/documentary
7,2669,Carter-Guzman,Centralized cohesive challenge,4500,14741,successful,227,DK,DKK,1608616800,1632200400,False,False,theater/plays
8,1114,Nunez-Richards,Exclusive attitude-oriented intranet,110100,21946,live,708,DK,DKK,1586322000,1615356000,False,False,theater/plays
9,970,"Rangel, Holt and Jones",Open-source fresh-thinking model,6200,3208,failed,44,US,USD,1628830800,1630386000,False,False,music/electric music

In [4]:
# Increase the column width for next dataframe
pd.set_option('max_colwidth', 400)
contact_info_df = pd.read_excel(crowdfunding_data, sheet_name="contact_info", header=2) # Skip 3 header rows (first is 0)
contact_info_df.head(10)

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}
5        {"contact_id": 2199, "name": "Samuel Sorgatz", "email": "samuel.sorgatz@gmail.com"}
6          {"contact_id": 5650, "name": "Socorro Luna", "email": "socorro.luna@hotmail.com"}
7     {"contact_id": 5889, "name": "Carolina Murray", "email": "carolina.murray@knight.com"}
8                 {"contact_id": 4842, "name": "Kayla Moon", "email": "kayla.moon@yahoo.de"}
9       {"contact_id": 3280, "name": "Ariadna Geisel", "email": "ariadna.geisel@rangel.com"}

### Sample dataframes

In [5]:
contact_info_df.tail(10)

991                    {"contact_id": 5500, "name": "Vincentio Sanders", "email": "vincentio.sanders@voila.fr"}
992                {"contact_id": 3494, "name": "Bettina Norbiato", "email": "bettina.norbiato@allen-lutz.org"}
993                        {"contact_id": 3924, "name": "Julio Renner", "email": "julio.renner@industrias.net"}
994                          {"contact_id": 3521, "name": "Jelena Stiffel", "email": "jelena.stiffel@trupp.de"}
995          {"contact_id": 5262, "name": "Guadalupe Munoz", "email": "guadalupe.munoz@murray-hamilton.com.au"}
996                    {"contact_id": 3684, "name": "Whitney Noack", "email": "whitney.noack@laboratorios.org"}
997              {"contact_id": 5784, "name": "Gelsomina Migliaccio", "email": "gelsomina.migliaccio@junk.com"}
998   {"contact_id": 1498, "name": "Evangelista Pereira", "email": "evangelista.pereira@thompson-peterson.biz"}
999                        {"contact_id": 6073, "name": "Gareth Comolli", "email": "gareth.comolli@tiscali.fr"}
1000                {"contact_id": 4939, "name": "Michelangelo Hess", "email": "michelangelo.hess@bouygtel.fr"}

In [6]:
# Run multiple times to get new random rows each time
contact_info_df.sample(n=10)

129   {"contact_id": 5501, "name": "Venancio Stadelmann", "email": "venancio.stadelmann@gmx.de"}
882           {"contact_id": 3173, "name": "Erin Weinhold", "email": "erin.weinhold@hotmail.fr"}
393    {"contact_id": 3365, "name": "Alessio Bruneau", "email": "alessio.bruneau@hotmail.co.uk"}
434      {"contact_id": 3176, "name": "Stephen Pratesi", "email": "stephen.pratesi@hotmail.com"}
263        {"contact_id": 2761, "name": "Laetitia Gallet", "email": "laetitia.gallet@aubry.org"}
116             {"contact_id": 6026, "name": "Laura Buckley", "email": "laura.buckley@ryan.org"}
339         {"contact_id": 4618, "name": "Heather Zimmer", "email": "heather.zimmer@bluemel.de"}
168         {"contact_id": 4951, "name": "Sergio Abbott", "email": "sergio.abbott@moore.net.au"}
739          {"contact_id": 6028, "name": "Jean Berthelot", "email": "jean.berthelot@oscuro.it"}
406  {"contact_id": 6055, "name": "Emmanuel Dominguez", "email": "emmanuel.dominguez@gmail.com"}

In [7]:
crowdfunding_info_df.tail(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
990,1561,Ortiz-Roberts,Devolved foreground customer loyalty,7800,6839,failed,64,US,USD,1623214800,1623992400,False,True,film & video/drama
991,2632,Ramirez LLC,Reduced reciprocal focus group,9800,11091,successful,241,US,USD,1607493600,1622005200,False,True,music/rock
992,439,Morrow Inc,Networked global migration,3100,13223,successful,132,US,USD,1592110800,1612850400,False,True,film & video/drama
993,461,Erickson-Rogers,De-engineered even-keeled definition,9800,7608,canceled,75,IT,EUR,1625288400,1625720400,False,True,photography/photography books
994,1419,"Leach, Rich and Price",Implemented bi-directional flexibility,141100,74073,failed,842,US,USD,1636956000,1638856800,False,True,publishing/translations
995,2986,Manning-Hamilton,Vision-oriented scalable definition,97300,153216,successful,2043,US,USD,1609221600,1622350800,False,True,food/food trucks
996,2031,Butler LLC,Future-proofed upward-trending migration,6600,4814,failed,112,US,USD,1634274000,1638252000,False,False,theater/plays
997,1627,Ball LLC,Right-sized full-range throughput,7600,4603,canceled,139,IT,EUR,1636174800,1639116000,False,False,theater/plays
998,2175,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600,37823,failed,374,US,USD,1602133200,1618117200,False,True,music/indie rock
999,1788,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100,62819,canceled,1122,US,USD,1609308000,1629262800,False,False,food/food trucks

In [8]:
crowdfunding_info_df.sample(n=10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
352,2514,"Adams, Willis and Sanchez",Expanded hybrid hardware,2800,977,failed,33,CA,CAD,1619326800,1625461200,False,False,theater/plays
273,2440,Thomas and Sons,Re-engineered heuristic forecast,7800,10704,successful,282,CA,CAD,1604469600,1626325200,False,False,theater/plays
593,1813,Hale-Hayes,Ameliorated client-driven open system,121600,188288,successful,4006,US,USD,1609826400,1637992800,False,False,film & video/animation
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
968,1755,Gonzalez-White,Open-architected disintermediate budgetary management,2400,8117,successful,114,US,USD,1608530400,1635310800,False,False,food/food trucks
752,1496,Lowery Group,Sharable motivating emulation,5800,5362,canceled,114,US,USD,1608789600,1630213200,False,True,theater/plays
193,3195,"Calhoun, Rogers and Long",Progressive discrete hub,6600,3012,failed,65,US,USD,1587790800,1616389200,True,False,music/indie rock
629,2940,"Jackson, Martinez and Ray",Multi-tiered executive toolset,85900,55476,failed,750,US,USD,1617598800,1642572000,False,True,theater/plays
322,1373,Hebert Group,Visionary asymmetric Graphical User Interface,117900,196377,successful,5168,US,USD,1616043600,1616389200,False,False,theater/plays
470,470,"Grimes, Holland and Sloan",Extended dedicated archive,3600,10289,successful,381,US,USD,1618549200,1634101200,False,False,technology/wearables

In [9]:
# Get a dataframe summary
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   company_name             1000 non-null   object
 2   blurb                    1000 non-null   object
 3   goal                     1000 non-null   int64
 4   pledged                  1000 non-null   int64
 5   outcome                  1000 non-null   object
 6   backers_count            1000 non-null   int64
 7   country                  1000 non-null   object
 8   currency                 1000 non-null   object
 9   launched_at              1000 non-null   int64
 10  deadline                 1000 non-null   int64
 11  staff_pick               1000 non-null   bool
 12  spotlight                1000 non-null   bool
 13  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(6), object(6)
memory usage: 95.8+ KB

In [10]:
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           1001 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

## 8.3.3

### Inspect

In [11]:
crowdfunding_info_df.columns

Index(['cf_id', 'company_name', 'blurb', 'goal', 'pledged', 'outcome',
       'backers_count', 'country', 'currency', 'launched_at', 'deadline',
       'staff_pick', 'spotlight', 'category & sub-category'],
      dtype='object')

In [12]:
crowdfunding_info_df['category & sub-category'].unique()

array(['food/food trucks', 'music/rock', 'technology/web',
       'theater/plays', 'film & video/documentary',
       'music/electric music', 'film & video/drama', 'music/indie rock',
       'technology/wearables', 'publishing/nonfiction',
       'film & video/animation', 'games/video games',
       'film & video/shorts', 'publishing/fiction',
       'photography/photography books', 'publishing/radio & podcasts',
       'music/metal', 'music/jazz', 'publishing/translations',
       'film & video/television', 'games/mobile games',
       'music/world music', 'film & video/science fiction',
       'journalism/audio'], dtype=object)

In [13]:
# This column has 24 unique values

### Plan

In [14]:
# Split category and sub-category values using code rather than "hard coding" (puttin them in manually)

### Execute

In [15]:
# Use str.split method with "/" as delimiter

In [16]:
# Assign the category and subcategory values to category and subcategory columns.
# Documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.split.html
crowdfunding_info_df[["category", "subcategory"]] = crowdfunding_info_df["category & sub-category"].str.split('/', n=1, expand=True)

In [17]:
crowdfunding_info_df.head(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
5,2057,Harris Group,Open-source optimizing database,7600,13195,successful,174,DK,DKK,1607666400,1630213200,False,False,theater/plays,theater,plays
6,1894,"Ortiz, Coleman and Mitchell",Operative upward-trending algorithm,5200,1090,failed,18,GB,GBP,1596171600,1620709200,False,False,film & video/documentary,film & video,documentary
7,2669,Carter-Guzman,Centralized cohesive challenge,4500,14741,successful,227,DK,DKK,1608616800,1632200400,False,False,theater/plays,theater,plays
8,1114,Nunez-Richards,Exclusive attitude-oriented intranet,110100,21946,live,708,DK,DKK,1586322000,1615356000,False,False,theater/plays,theater,plays
9,970,"Rangel, Holt and Jones",Open-source fresh-thinking model,6200,3208,failed,44,US,USD,1628830800,1630386000,False,False,music/electric music,music,electric music

### Assign unique id numbers to all categories and subcategories

In [18]:
print(crowdfunding_info_df["category"].unique())
print(crowdfunding_info_df["subcategory"].unique())

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']
['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']

In [19]:
# 9 categories
# 24 subcategories

### Create 2 new dataframes for category and subcategory

In [20]:
# Get the unique categories and subcategories into different LISTS
categories = crowdfunding_info_df["category"].unique()
subcategories = crowdfunding_info_df["subcategory"].unique()
print(categories)
print()
print(subcategories)

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']

['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']